// Asset Configuration
// Maps category groups to their form fields and card display fields
// Also contains all available categories with their metadata

export const categoryGroupConfig = {
  Assets: {
    formFields: [
      'Asset Name',
      'Description',
      'Category',
      'Location',
      'Make/Model/Year',
      'Estimated Value',
      'Purchase Date',
      'Purchase Price',
      'Condition',
      'Ownership Type',
      'Image',
      'Serial Number',
      'Proof of Ownership',
      'Appraisal Document',
      'Tags',
    ],
    cardFields: [
      'Asset Name',
      'Category',
      'Location',
      'Estimated Value',
      'Last Appraisal',
      'Condition',
      'Ownership Type',
      'Image',
    ],
  },
  Portfolio: {
    // 'Asset Type' maps to the backend's `asset_type`. It used to read
    // 'Investment Type' — a field that exists nowhere in the backend, so every
    // value the user picked was silently dropped by Pydantic's `extra: ignore`.
    formFields: [
      'Asset Name',
      'Asset Type',
      'Category',
      'Institution',
      'Account Number (masked)',
      'Acquisition Date',
      'Purchase Price',
      'Current Value',
      'Currency',
      'Risk Level',
      'Investment Horizon',
    ],
    cardFields: [
      'Asset Name',
      'Asset Type',
      'Category',
      'Institution',
      'Current Value',
      'Currency',
      'Risk Level',
    ],
  },
  Liabilities: {
    formFields: [
      'Debt Type',
      'Creditor Name',
      'Amount Owed',
      'Interest Rate',
      'Start Date',
      'Maturity Date',
      'Payment Frequency',
      'Collateral (if any)',
      'Currency',
    ],
    cardFields: ['Debt Type', 'Creditor', 'Amount Owed', 'Interest Rate', 'Due Date'],
  },
  'Shadow Wealth': {
    formFields: [
      'Wealth Type',
      'Description',
      'Estimated Value',
      'Expected Date',
      'Documentation (if any)',
      'Source Entity',
      'Beneficiary',
    ],
    cardFields: ['Wealth Type', 'Description', 'Estimated Value', 'Expected Date'],
  },
  Philanthropy: {
    formFields: [
      'Fund/Vehicle Name',
      'Type (Foundation/DAF/etc)',
      'Purpose',
      'Start Date',
      'Contribution Value',
      'Institution',
      'Jurisdiction',
      'Impact Area',
    ],
    cardFields: ['Fund Name', 'Type', 'Contribution Value', 'Impact Area'],
  },
  Lifestyle: {
    formFields: [
      'Service Type',
      'Vendor Name',
      'Membership/Service ID',
      'Start Date',
      'End Date',
      'Associated Asset (optional)',
      'Location',
      'Annual Cost',
    ],
    cardFields: ['Service Type', 'Vendor', 'Membership ID', 'Annual Cost'],
  },
  Governance: {
    formFields: [
      'Record Type (KYC, Legal, Audit)',
      'Document Name',
      'Related Asset/User',
      'Upload Date',
      'Expiry Date',
      'Verified By',
      'Notes',
    ],
    cardFields: [
      'Record Type',
      'Document Name',
      'Related Asset/User',
      'Upload Date',
      'Expiry Date',
    ],
  },
};

// All categories organized by category type
export const allCategories = [
  // Assets (Physical, Alternative, Lifestyle)
  {
    id: 'Yachts',
    name: 'Yachts',
    categoryGroup: 'Assets',
    description: 'Privately owned or chartered luxury boats and vessels',
    icon: '🛥️',
    iconFile: 'yacht.svg',
  },
  {
    id: 'Private Jets',
    name: 'Private Jets',
    categoryGroup: 'Assets',
    description: 'Owned or fractional aircraft holdings',
    icon: '✈️',
    iconFile: 'Jets.svg',
  },
  {
    id: 'Real Estate',
    name: 'Real Estate',
    categoryGroup: 'Assets',
    description: 'Residential, commercial, or investment properties',
    icon: '🏠',
    iconFile: 'Realstat.svg',
  },
  {
    id: 'Vehicles',
    name: 'Vehicles',
    categoryGroup: 'Assets',
    description: 'Luxury or collectible cars and motorcycles',
    icon: '🚗',
    iconFile: 'vehicels.svg',
  },
  {
    id: 'Art & Collectibles',
    name: 'Art & Collectibles',
    categoryGroup: 'Assets',
    description: 'Paintings, sculptures, rare cultural items',
    icon: '🎨',
    iconFile: 'Art_collectibles.svg',
  },
  {
    id: 'Watches & Jewelry',
    name: 'Watches & Jewelry',
    categoryGroup: 'Assets',
    description: 'Timepieces and precious stones',
    icon: '⌚️💎',
    iconFile: 'watches_jawelry.svg',
  },
  {
    id: 'Precious Metals',
    name: 'Precious Metals',
    categoryGroup: 'Assets',
    description: 'Gold, silver, and platinum bars',
    icon: '🪙',
    iconFile: null,
  },
  {
    id: 'Wine & Whiskey',
    name: 'Wine & Whiskey',
    categoryGroup: 'Assets',
    description: 'Investment-grade alcohol collections',
    icon: '🍷',
    iconFile: null,
  },
  {
    id: 'Luxury Furniture',
    name: 'Luxury Furniture',
    categoryGroup: 'Assets',
    description: 'Custom or antique high-end furnishings',
    icon: '🛋️',
    iconFile: null,
  },
  {
    id: 'Antiques',
    name: 'Antiques',
    categoryGroup: 'Assets',
    description: 'Historical artifacts of value',
    icon: '🗿',
    iconFile: null,
  },
  {
    id: 'Fine Instruments',
    name: 'Fine Instruments',
    categoryGroup: 'Assets',
    description: 'Collectible musical instruments',
    icon: '🎻',
    iconFile: null,
  },
  {
    id: 'Luxury Memorabilia',
    name: 'Luxury Memorabilia',
    categoryGroup: 'Assets',
    description: 'Sports, movie, and cultural collectibles',
    icon: '🏆',
    iconFile: null,
  },
  {
    id: 'Farmland & Agri Land',
    name: 'Farmland & Agri Land',
    categoryGroup: 'Assets',
    description: 'Productive or appreciating agricultural land',
    icon: '🌾',
    iconFile: null,
  },
  {
    id: 'Private Company Equity',
    name: 'Private Company Equity',
    categoryGroup: 'Assets',
    description: 'Equity in startups or private ventures',
    icon: '🏢',
    iconFile: null,
  },
  {
    id: 'Intellectual Property',
    name: 'Intellectual Property',
    categoryGroup: 'Assets',
    description: 'Patents, trademarks, or copyrights',
    icon: '📄⚙️',
    iconFile: null,
  },
  {
    id: 'Racehorses & Animals',
    name: 'Racehorses & Animals',
    categoryGroup: 'Assets',
    description: 'High-value animals for racing or breeding',
    icon: '🐎',
    iconFile: null,
  },
  {
    id: 'Fractional Ownerships',
    name: 'Fractional Ownerships',
    categoryGroup: 'Assets',
    description: 'Shared vacation homes, jets, or yachts',
    icon: '🧩',
    iconFile: null,
  },
  {
    id: 'Classic Motorcycles',
    name: 'Classic Motorcycles',
    categoryGroup: 'Assets',
    description: 'Vintage bikes with appreciation potential',
    icon: '🏍️',
    iconFile: null,
  },
  {
    id: 'Green Assets',
    name: 'Green Assets',
    categoryGroup: 'Assets',
    description: 'Carbon offsets, green bonds, solar farms',
    icon: '🌱',
    iconFile: null,
  },
  {
    id: 'Digital Collectibles',
    name: 'Digital Collectibles',
    categoryGroup: 'Assets',
    description: 'NFTs and digital ownership assets',
    icon: '🖼️',
    iconFile: null,
  },
  {
    id: 'Couture & Designer Wear',
    name: 'Couture & Designer Wear',
    categoryGroup: 'Assets',
    description: 'Limited-edition fashion garments',
    icon: '👗',
    iconFile: null,
  },
  {
    id: 'Boats & Watercraft',
    name: 'Boats & Watercraft',
    categoryGroup: 'Assets',
    description: 'Non-luxury boats or personal marine vehicles',
    icon: '🚤',
    iconFile: null,
  },
  {
    id: 'Raw Precious Stones',
    name: 'Raw Precious Stones',
    categoryGroup: 'Assets',
    description: 'Uncut investment-grade stones',
    icon: '🔹',
    iconFile: null,
  },
  {
    id: 'Vaulted/Stored Assets',
    name: 'Vaulted/Stored Assets',
    categoryGroup: 'Assets',
    description: 'Items stored in safes or secure vaults',
    icon: '🏦',
    iconFile: null,
  },
  // Portfolio (Financial, Digital, Structured)
  {
    id: 'Crypto Assets',
    name: 'Crypto Assets',
    categoryGroup: 'Portfolio',
    description: 'Bitcoin, Ethereum, other digital currencies',
    icon: '₿',
    iconFile: null,
  },
  {
    id: 'Cash Flow Accounts',
    name: 'Cash Flow Accounts',
    categoryGroup: 'Portfolio',
    description: 'Bank, savings, or checking account inflows',
    icon: '💵',
    iconFile: null,
  },
  {
    id: 'Trade Engine',
    name: 'Trade Engine',
    categoryGroup: 'Portfolio',
    description: 'Stock and fund transactions',
    icon: '📈',
    iconFile: null,
  },
  {
    id: 'Public Equities',
    name: 'Public Equities',
    categoryGroup: 'Portfolio',
    description: 'Stocks and market shares',
    icon: '🏛️',
    iconFile: null,
  },
  {
    id: 'Fixed Income',
    name: 'Fixed Income',
    categoryGroup: 'Portfolio',
    description: 'Government and corporate bonds',
    icon: '🏦📃',
    iconFile: null,
  },
  {
    id: 'ETFs & Index Funds',
    name: 'ETFs & Index Funds',
    categoryGroup: 'Portfolio',
    description: 'Market-tracking investment vehicles',
    icon: '🧾',
    iconFile: null,
  },
  {
    id: 'Mutual Funds',
    name: 'Mutual Funds',
    categoryGroup: 'Portfolio',
    description: 'Professionally managed pooled assets',
    icon: '💼',
    iconFile: null,
  },
  {
    id: 'Private Equity',
    name: 'Private Equity',
    categoryGroup: 'Portfolio',
    description: 'Non-public investment holdings',
    icon: '🔐',
    iconFile: null,
  },
  {
    id: 'Hedge Funds',
    name: 'Hedge Funds',
    categoryGroup: 'Portfolio',
    description: 'High-risk, high-reward investment pools',
    icon: '♠️',
    iconFile: null,
  },
  {
    id: 'Commodities',
    name: 'Commodities',
    categoryGroup: 'Portfolio',
    description: 'Oil, gas, grain, etc.',
    icon: '🛢️🌽',
    iconFile: null,
  },
  {
    id: 'Structured Products',
    name: 'Structured Products',
    categoryGroup: 'Portfolio',
    description: 'Custom-linked notes and certificates',
    icon: '🧱',
    iconFile: null,
  },
  {
    id: 'Foreign Currency',
    name: 'Foreign Currency',
    categoryGroup: 'Portfolio',
    description: 'FX and multicurrency holdings',
    icon: '💱',
    iconFile: null,
  },
  {
    id: 'Offshore Accounts',
    name: 'Offshore Accounts',
    categoryGroup: 'Portfolio',
    description: 'Non-domestic financial holdings',
    icon: '🌍💳',
    iconFile: null,
  },
  {
    id: 'REITs & Real Estate Funds',
    name: 'REITs & Real Estate Funds',
    categoryGroup: 'Portfolio',
    description: 'Property-backed investment vehicles',
    icon: '🏗️',
    iconFile: null,
  },
  {
    id: 'Annuities',
    name: 'Annuities',
    categoryGroup: 'Portfolio',
    description: 'Retirement-linked insurance payouts',
    icon: '📆💸',
    iconFile: null,
  },
  {
    id: 'Investment-Linked Insurance',
    name: 'Investment-Linked Insurance',
    categoryGroup: 'Portfolio',
    description: 'Insurance with cash value and growth',
    icon: '🛡️📊',
    iconFile: null,
  },
  {
    id: 'Pension & Retirement',
    name: 'Pension & Retirement',
    categoryGroup: 'Portfolio',
    description: '401(k), IRA, or similar plans',
    icon: '🧓',
    iconFile: null,
  },
  {
    id: 'Crowdfunding Investments',
    name: 'Crowdfunding Investments',
    categoryGroup: 'Portfolio',
    description: 'Startup or Reg CF investments',
    icon: '🌐',
    iconFile: null,
  },
  {
    id: 'Digital Assets (Non-Crypto)',
    name: 'Digital Assets (Non-Crypto)',
    categoryGroup: 'Portfolio',
    description: 'Tokenized securities or virtual assets',
    icon: '🪙💻',
    iconFile: null,
  },
  {
    id: 'ESG & Carbon Credits',
    name: 'ESG & Carbon Credits',
    categoryGroup: 'Portfolio',
    description: 'Environmentally sustainable assets',
    icon: '🌍✅',
    iconFile: null,
  },
  {
    id: 'Margin & Credit',
    name: 'Margin & Credit',
    categoryGroup: 'Portfolio',
    description: 'Borrowed capital for investing',
    icon: '💳📉',
    iconFile: null,
  },
  {
    id: 'Royalty Streams',
    name: 'Royalty Streams',
    categoryGroup: 'Portfolio',
    description: 'IP income from licensing or royalties',
    icon: '🎶',
    iconFile: null,
  },
  {
    id: 'Litigation Finance',
    name: 'Litigation Finance',
    categoryGroup: 'Portfolio',
    description: 'Investment in legal outcomes',
    icon: '⚖️💼',
    iconFile: null,
  },
  {
    id: 'Precious Metal ETFs',
    name: 'Precious Metal ETFs',
    categoryGroup: 'Portfolio',
    description: 'Gold/silver traded on exchanges',
    icon: '📊🪙',
    iconFile: null,
  },
  {
    id: 'Derivatives & Options',
    name: 'Derivatives & Options',
    categoryGroup: 'Portfolio',
    description: 'Futures, options, and hedging contracts',
    icon: '📉',
    iconFile: null,
  },
  {
    id: 'Trusts / Foundations',
    name: 'Trusts / Foundations',
    categoryGroup: 'Portfolio',
    description: 'Structured philanthropic or estate tools',
    icon: '🏛️❤️',
    iconFile: null,
  },
  {
    id: 'Cash Management',
    name: 'Cash Management',
    categoryGroup: 'Portfolio',
    description: 'Treasury and cash liquidity operations',
    icon: '💼💧',
    iconFile: null,
  },
  {
    id: 'Stablecoins & CBDCs',
    name: 'Stablecoins & CBDCs',
    categoryGroup: 'Portfolio',
    description: 'Government-backed or pegged digital assets',
    icon: '🪙🏦',
    iconFile: null,
  },
  {
    id: 'DeFi Instruments',
    name: 'DeFi Instruments',
    categoryGroup: 'Portfolio',
    description: 'Decentralized protocols and yield farming',
    icon: '🧬💹',
    iconFile: null,
  },
  {
    id: 'Convertible Notes',
    name: 'Convertible Notes',
    categoryGroup: 'Portfolio',
    description: 'Debt instruments convertible into equity',
    icon: '🔄📃',
    iconFile: null,
  },
  {
    id: 'Tax-Deferred Investments',
    name: 'Tax-Deferred Investments',
    categoryGroup: 'Portfolio',
    description: 'Assets with delayed tax exposure',
    icon: '🧾🕒',
    iconFile: null,
  },
  {
    id: 'Stock Options / RSUs',
    name: 'Stock Options / RSUs',
    categoryGroup: 'Portfolio',
    description: 'Employee equity compensation',
    icon: '🧑‍💼📈',
    iconFile: null,
  },
  {
    id: 'Micro-Investments',
    name: 'Micro-Investments',
    categoryGroup: 'Portfolio',
    description: 'Round-up or fractional investing tools',
    icon: '📲',
    iconFile: null,
  },
  // Liabilities & Debts
  {
    id: 'Mortgages',
    name: 'Mortgages',
    categoryGroup: 'Liabilities',
    description: 'Loans for real estate ownership',
    icon: '🏠💸',
    iconFile: null,
  },
  {
    id: 'Personal Loans',
    name: 'Personal Loans',
    categoryGroup: 'Liabilities',
    description: 'Credit or unsecured borrowing',
    icon: '🤝',
    iconFile: null,
  },
  {
    id: 'Business Loans',
    name: 'Business Loans',
    categoryGroup: 'Liabilities',
    description: 'Venture or company-backed debts',
    icon: '🏢💳',
    iconFile: null,
  },
  {
    id: 'Credit Cards',
    name: 'Credit Cards',
    categoryGroup: 'Liabilities',
    description: 'Revolving personal credit',
    icon: '💳',
    iconFile: null,
  },
  {
    id: 'Auto / Yacht Loans',
    name: 'Auto / Yacht Loans',
    categoryGroup: 'Liabilities',
    description: 'Installment debt for vehicles',
    icon: '🚗💰',
    iconFile: null,
  },
  {
    id: 'Margin Loans',
    name: 'Margin Loans',
    categoryGroup: 'Liabilities',
    description: 'Borrowing against investment assets',
    icon: '📈💳',
    iconFile: null,
  },
  {
    id: 'Lines of Credit',
    name: 'Lines of Credit',
    categoryGroup: 'Liabilities',
    description: 'Flexible borrowing limits',
    icon: '🧾🌀',
    iconFile: null,
  },
  {
    id: 'Tax Liabilities',
    name: 'Tax Liabilities',
    categoryGroup: 'Liabilities',
    description: 'Outstanding government obligations',
    icon: '🧾🏛️',
    iconFile: null,
  },
  {
    id: 'Deferred Payments',
    name: 'Deferred Payments',
    categoryGroup: 'Liabilities',
    description: 'Scheduled future financial obligations',
    icon: '📅💵',
    iconFile: null,
  },
  {
    id: 'Lease Agreements',
    name: 'Lease Agreements',
    categoryGroup: 'Liabilities',
    description: 'Property or asset leasing contracts',
    icon: '📝🏠',
    iconFile: null,
  },
  // Shadow & Anticipated Wealth
  {
    id: 'Pending Inheritance',
    name: 'Pending Inheritance',
    categoryGroup: 'Shadow Wealth',
    description: 'Future estate-based assets',
    icon: '👪💼',
    iconFile: null,
  },
  {
    id: 'Unvested Stock / RSUs',
    name: 'Unvested Stock / RSUs',
    categoryGroup: 'Shadow Wealth',
    description: 'Company equity not yet vested',
    icon: '📊🔒',
    iconFile: null,
  },
  {
    id: 'Deferred Compensation',
    name: 'Deferred Compensation',
    categoryGroup: 'Shadow Wealth',
    description: 'Future salary or incentive payments',
    icon: '⏳💰',
    iconFile: null,
  },
  {
    id: 'Marital / Shared Assets',
    name: 'Marital / Shared Assets',
    categoryGroup: 'Shadow Wealth',
    description: 'Co-owned or prenup-structured holdings',
    icon: '💍🏠',
    iconFile: null,
  },
  {
    id: 'Trust Allocations',
    name: 'Trust Allocations',
    categoryGroup: 'Shadow Wealth',
    description: 'Assets allocated via structured trusts',
    icon: '🗃️',
    iconFile: null,
  },
  {
    id: 'Legal Settlements',
    name: 'Legal Settlements',
    categoryGroup: 'Shadow Wealth',
    description: 'Expected outcomes from legal disputes',
    icon: '🧾⚖️',
    iconFile: null,
  },
  {
    id: 'Anticipated Exit Proceeds',
    name: 'Anticipated Exit Proceeds',
    categoryGroup: 'Shadow Wealth',
    description: 'Future company or asset sale estimates',
    icon: '📈⏳',
    iconFile: null,
  },
  {
    id: 'Brand / IP Equity',
    name: 'Brand / IP Equity',
    categoryGroup: 'Shadow Wealth',
    description: 'Value of reputation, trademarks, and brand assets',
    icon: '🧠📢',
    iconFile: null,
  },
  // Philanthropy & Impact
  {
    id: 'Foundations',
    name: 'Foundations',
    categoryGroup: 'Philanthropy',
    description: 'Registered charitable organizations',
    icon: '🤝🏛️',
    iconFile: null,
  },
  {
    id: 'Donor-Advised Funds',
    name: 'Donor-Advised Funds',
    categoryGroup: 'Philanthropy',
    description: 'Managed giving accounts with donor control',
    icon: '🎁',
    iconFile: null,
  },
  {
    id: 'Endowments',
    name: 'Endowments',
    categoryGroup: 'Philanthropy',
    description: 'Capital for institutions or causes',
    icon: '🎓💰',
    iconFile: null,
  },
  {
    id: 'Impact Investments',
    name: 'Impact Investments',
    categoryGroup: 'Philanthropy',
    description: 'Social and financial return assets',
    icon: '🌱📈',
    iconFile: null,
  },
  {
    id: 'Scholarship Trusts',
    name: 'Scholarship Trusts',
    categoryGroup: 'Philanthropy',
    description: 'Education-oriented gifting structures',
    icon: '🧑‍🎓🎓',
    iconFile: null,
  },
  // Lifestyle & Concierge
  {
    id: 'Travel Concierge',
    name: 'Travel Concierge',
    categoryGroup: 'Lifestyle',
    description: 'Private bookings, charters, itineraries',
    icon: '🧳✈️',
    iconFile: null,
  },
  {
    id: 'Event & Auction Access',
    name: 'Event & Auction Access',
    categoryGroup: 'Lifestyle',
    description: 'Invitations to elite global events',
    icon: '🎟️🏆',
    iconFile: null,
  },
  {
    id: 'Club Memberships',
    name: 'Club Memberships',
    categoryGroup: 'Lifestyle',
    description: 'Golf, yacht, or exclusive social clubs',
    icon: '🏌️‍♂️🚤',
    iconFile: null,
  },
  {
    id: 'Property Maintenance',
    name: 'Property Maintenance',
    categoryGroup: 'Lifestyle',
    description: 'Management of luxury homes and rentals',
    icon: '🧰🏡',
    iconFile: null,
  },
  {
    id: 'Insurance Management',
    name: 'Insurance Management',
    categoryGroup: 'Lifestyle',
    description: 'Coverage tracking and renewals',
    icon: '🛡️',
    iconFile: null,
  },
  {
    id: 'Family Office Services',
    name: 'Family Office Services',
    categoryGroup: 'Lifestyle',
    description: 'Integrated lifestyle and finance support',
    icon: '🧑‍💼🏦',
    iconFile: null,
  },
  // Compliance & Governance
  {
    id: 'KYC & AML Records',
    name: 'KYC & AML Records',
    categoryGroup: 'Governance',
    description: 'Identity verification and risk checks',
    icon: '🪪🔍',
    iconFile: null,
  },
  {
    id: 'Audit Logs',
    name: 'Audit Logs',
    categoryGroup: 'Governance',
    description: 'System and action history',
    icon: '📜🕵️',
    iconFile: null,
  },
  {
    id: 'Legal Agreements',
    name: 'Legal Agreements',
    categoryGroup: 'Governance',
    description: 'Contracts, NDAs, and regulatory documents',
    icon: '📄✍️',
    iconFile: null,
  },
  {
    id: 'Regulatory Filings',
    name: 'Regulatory Filings',
    categoryGroup: 'Governance',
    description: 'Disclosures and formal compliance documents',
    icon: '🏛️📤',
    iconFile: null,
  },
];

// Helper function to get category group from category
export const getCategoryGroup = categoryId => {
  const category = allCategories.find(cat => cat.id === categoryId);
  return category ? category.categoryGroup : 'Assets';
};

// Helper function to get form fields for a category
export const getFormFieldsForCategory = categoryId => {
  const categoryGroup = getCategoryGroup(categoryId);
  return categoryGroupConfig[categoryGroup]?.formFields || [];
};

// Helper function to get card fields for a category
export const getCardFieldsForCategory = categoryId => {
  const categoryGroup = getCategoryGroup(categoryId);
  return categoryGroupConfig[categoryGroup]?.cardFields || [];
};

// Get categories by group
export const getCategoriesByGroup = groupName => {
  return allCategories.filter(cat => cat.categoryGroup === groupName);
};

// Get all unique category groups
export const getCategoryGroups = () => {
  return [...new Set(allCategories.map(cat => cat.categoryGroup))];
};

