// Icon mapping for categories using react-icons
import {
  FaHome,
  FaCar,
  FaPalette,
  FaGem,
  FaCoins,
  FaWineBottle,
  FaTrophy,
  FaBuilding,
  FaFileAlt,
  FaHorse,
  FaMotorcycle,
  FaLeaf,
  FaImage,
  FaShip,
  FaLock,
  FaPlane,
} from 'react-icons/fa';
import {
  MdAccountBalance,
  MdTrendingUp,
  MdShowChart,
  MdAccountBalanceWallet,
  MdSavings,
  MdLocalAtm,
  MdBusiness,
  MdLock,
  MdAttachMoney,
  MdEuro,
  MdLanguage,
  MdPublic,
  MdRealEstateAgent,
  MdCalendarToday,
  MdSecurity,
  MdGroups,
  MdToken,
  MdEco,
  MdCreditCard,
  MdMusicNote,
  MdGavel,
  MdBarChart,
  MdSwapHoriz,
  MdSchedule,
  MdWork,
  MdPhoneIphone,
  MdNetworkWifi,
} from 'react-icons/md';
import {
  HiHome,
  HiBriefcase,
  HiCreditCard,
  HiDocumentText,
  HiCalendar,
  HiClock,
  HiUserGroup,
  HiChartBar,
  HiLightBulb,
} from 'react-icons/hi';
import {
  IoWalletOutline,
  IoShieldCheckmark,
  IoDocumentTextOutline,
  IoFileTrayFullOutline,
} from 'react-icons/io5';
// Using only icons that definitely exist - replacing Gi icons with alternatives
// Gi icons are unreliable, using Md, Hi, Fa, and Io5 instead

// Category icon mapping
export const getCategoryIcon = (categoryId) => {
  const iconMap = {
    // Assets
    'Yachts': FaShip,
    'Private Jets': FaPlane,
    'Real Estate': FaHome,
    'Vehicles': FaCar,
    'Art & Collectibles': FaPalette,
    'Watches & Jewelry': FaGem,
    'Precious Metals': FaCoins,
    'Wine & Whiskey': FaWineBottle,
    'Luxury Furniture': FaHome,
    'Antiques': FaTrophy,
    'Fine Instruments': FaFileAlt,
    'Luxury Memorabilia': FaTrophy,
    'Farmland & Agri Land': FaLeaf,
    'Private Company Equity': FaBuilding,
    'Intellectual Property': FaFileAlt,
    'Racehorses & Animals': FaHorse,
    'Fractional Ownerships': FaBuilding,
    'Classic Motorcycles': FaMotorcycle,
    'Green Assets': FaLeaf,
    'Digital Collectibles': FaImage,
    'Couture & Designer Wear': FaImage,
    'Boats & Watercraft': FaShip,
    'Raw Precious Stones': FaGem,
    'Vaulted/Stored Assets': FaLock,
    
    // Portfolio
    'Crypto Assets': MdAccountBalanceWallet,
    'Cash Flow Accounts': MdAccountBalanceWallet,
    'Trade Engine': MdTrendingUp,
    'Public Equities': MdShowChart,
    'Fixed Income': MdAccountBalance,
    'ETFs & Index Funds': MdSavings,
    'Mutual Funds': MdAccountBalance,
    'Private Equity': MdBusiness,
    'Hedge Funds': MdLock,
    'Commodities': MdLocalAtm,
    'Structured Products': MdBusiness,
    'Foreign Currency': MdEuro,
    'Offshore Accounts': MdPublic,
    'REITs & Real Estate Funds': MdRealEstateAgent,
    'Annuities': MdCalendarToday,
    'Investment-Linked Insurance': MdSecurity,
    'Pension & Retirement': MdCalendarToday,
    'Crowdfunding Investments': MdGroups,
    'Digital Assets (Non-Crypto)': MdToken,
    'ESG & Carbon Credits': MdEco,
    'Margin & Credit': MdCreditCard,
    'Royalty Streams': MdMusicNote,
    'Litigation Finance': MdGavel,
    'Precious Metal ETFs': MdBarChart,
    'Derivatives & Options': MdSwapHoriz,
    'Trusts / Foundations': MdSchedule,
    'Cash Management': MdWork,
    'Stablecoins & CBDCs': MdPhoneIphone,
    'DeFi Instruments': MdNetworkWifi,
    'Convertible Notes': MdSwapHoriz,
    'Tax-Deferred Investments': MdSchedule,
    'Stock Options / RSUs': MdWork,
    'Micro-Investments': MdPhoneIphone,
    
    // Liabilities
    'Mortgages': HiHome,
    'Personal Loans': HiUserGroup,
    'Business Loans': HiBriefcase,
    'Credit Cards': HiCreditCard,
    'Auto / Yacht Loans': HiCreditCard,
    'Margin Loans': HiDocumentText,
    'Lines of Credit': HiCalendar,
    'Tax Liabilities': HiClock,
    'Deferred Payments': HiUserGroup,
    'Lease Agreements': HiDocumentText,
    
    // Shadow Wealth
    'Pending Inheritance': HiChartBar,
    'Unvested Stock / RSUs': HiLightBulb,
    'Deferred Compensation': IoWalletOutline,
    'Marital / Shared Assets': IoShieldCheckmark,
    'Trust Allocations': IoDocumentTextOutline,
    'Legal Settlements': IoFileTrayFullOutline,
    'Anticipated Exit Proceeds': HiChartBar,
    'Brand / IP Equity': HiLightBulb,
    
    // Philanthropy
    'Foundations': IoWalletOutline,
    'Donor-Advised Funds': IoShieldCheckmark,
    'Endowments': IoDocumentTextOutline,
    'Impact Investments': IoFileTrayFullOutline,
    'Scholarship Trusts': HiUserGroup,
    
    // Lifestyle
    'Travel Concierge': HiBriefcase,
    'Event & Auction Access': FaTrophy,
    'Club Memberships': FaGem,
    'Property Maintenance': FaHome,
    'Insurance Management': MdSecurity,
    'Family Office Services': FaBuilding,
    
    // Governance
    'KYC & AML Records': IoDocumentTextOutline,
    'Audit Logs': HiCalendar,
    'Legal Agreements': HiDocumentText,
    'Regulatory Filings': HiDocumentText,
  };

  return iconMap[categoryId] || FaFileAlt; // Default icon
};
